import { test, expect } from "bun:test"
import { generateCacheKey } from "../lib"

test("Different trace thicknesses should result in different cache keys", () => {
  const {
    cacheKey: cacheKey1,
    normalizedAutoroutingJson: normalizedAutoroutingJson1,
  } = generateCacheKey(circuitJsonWithTraceThickness1 as any)
  const {
    cacheKey: cacheKey2,
    normalizedAutoroutingJson: normalizedAutoroutingJson2,
  } = generateCacheKey(circuitJsonWithTraceThickness2 as any)

  expect(cacheKey1).toMatchInlineSnapshot(`"16cc07390bc734c2249bf1f2d682f1fd"`)
  expect(normalizedAutoroutingJson1).toMatchInlineSnapshot(`
    {
      "allowed_layers": 1,
      "net_properties": {
        "1": {
          "trace_thickness": "0.30",
        },
      },
      "nets_to_route": [
        1,
      ],
      "sorted_normalized_objects": [
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": null,
          "type": "rect_pad",
          "width": "0.60",
          "x": "-2.50",
          "y": "0.00",
        },
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": 1,
          "type": "rect_pad",
          "width": "0.60",
          "x": "-3.50",
          "y": "0.00",
        },
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": 1,
          "type": "rect_pad",
          "width": "0.60",
          "x": "2.50",
          "y": "0.00",
        },
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": null,
          "type": "rect_pad",
          "width": "0.60",
          "x": "3.50",
          "y": "0.00",
        },
      ],
    }
  `)
  expect(cacheKey2).toMatchInlineSnapshot(`"052f0527363a234dd8d0db2185fd3ff1"`)
  expect(normalizedAutoroutingJson2).toMatchInlineSnapshot(`
    {
      "allowed_layers": 1,
      "net_properties": {
        "1": {
          "trace_thickness": "0.15",
        },
      },
      "nets_to_route": [
        1,
      ],
      "sorted_normalized_objects": [
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": null,
          "type": "rect_pad",
          "width": "0.60",
          "x": "-2.50",
          "y": "0.00",
        },
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": 1,
          "type": "rect_pad",
          "width": "0.60",
          "x": "-3.50",
          "y": "0.00",
        },
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": 1,
          "type": "rect_pad",
          "width": "0.60",
          "x": "2.50",
          "y": "0.00",
        },
        {
          "height": "0.60",
          "layers": [
            "top",
          ],
          "net": null,
          "type": "rect_pad",
          "width": "0.60",
          "x": "3.50",
          "y": "0.00",
        },
      ],
    }
  `)
})

const circuitJsonWithTraceThickness1 = [
  {
    type: "source_port",
    source_port_id: "source_port_0",
    name: "pin1",
    pin_number: 1,
    port_hints: ["anode", "pos", "left", "pin1", "1"],
    source_component_id: "source_component_0",
  },
  {
    type: "source_port",
    source_port_id: "source_port_1",
    name: "pin2",
    pin_number: 2,
    port_hints: ["cathode", "neg", "right", "pin2", "2"],
    source_component_id: "source_component_0",
  },
  {
    type: "source_component",
    source_component_id: "source_component_0",
    ftype: "simple_resistor",
    name: "R1",
    resistance: 1000,
    display_resistance: "1kΩ",
  },
  {
    type: "source_port",
    source_port_id: "source_port_2",
    name: "pin1",
    pin_number: 1,
    port_hints: ["anode", "pos", "left", "pin1", "1"],
    source_component_id: "source_component_1",
  },
  {
    type: "source_port",
    source_port_id: "source_port_3",
    name: "pin2",
    pin_number: 2,
    port_hints: ["cathode", "neg", "right", "pin2", "2"],
    source_component_id: "source_component_1",
  },
  {
    type: "source_component",
    source_component_id: "source_component_1",
    ftype: "simple_capacitor",
    name: "C1",
    capacitance: 1e-9,
    display_capacitance: "1nF",
  },
  {
    type: "source_group",
    source_group_id: "source_group_0",
    is_subcircuit: true,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_0",
    connected_source_port_ids: ["source_port_0", "source_port_2"],
    connected_source_net_ids: [],
    max_length: null,
    display_name: ".R1 > .pin1 to .C1 > .pin1",
    subcircuit_connectivity_map_key: "unnamedsubcircuit27_connectivity_net0",
    min_trace_thickness: 0.3,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_0",
    center: {
      x: 3,
      y: 0,
    },
    width: 1.5999999999999996,
    height: 0.6000000000000001,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_0",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_1",
    center: {
      x: -3,
      y: 0,
    },
    width: 1.5999999999999996,
    height: 0.6000000000000001,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_1",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_board",
    pcb_board_id: "pcb_board_0",
    center: {
      x: 0,
      y: 0,
    },
    thickness: 1.4,
    num_layers: 4,
    width: 10,
    height: 10,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_0",
    pcb_component_id: "pcb_component_0",
    pcb_port_id: "pcb_port_0",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["1", "left"],
    x: 2.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_0",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: 2.5,
    y: 0,
    pcb_component_id: "pcb_component_0",
    pcb_smtpad_id: "pcb_smtpad_0",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_1",
    pcb_component_id: "pcb_component_0",
    pcb_port_id: "pcb_port_1",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["2", "right"],
    x: 3.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_1",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: 3.5,
    y: 0,
    pcb_component_id: "pcb_component_0",
    pcb_smtpad_id: "pcb_smtpad_1",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_2",
    pcb_component_id: "pcb_component_1",
    pcb_port_id: "pcb_port_2",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["1", "left"],
    x: -3.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_2",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: -3.5,
    y: 0,
    pcb_component_id: "pcb_component_1",
    pcb_smtpad_id: "pcb_smtpad_2",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_3",
    pcb_component_id: "pcb_component_1",
    pcb_port_id: "pcb_port_3",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["2", "right"],
    x: -2.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_3",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: -2.5,
    y: 0,
    pcb_component_id: "pcb_component_1",
    pcb_smtpad_id: "pcb_smtpad_3",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_0",
    pcb_component_id: "pcb_component_0",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: 2.5,
    y: 0,
    source_port_id: "source_port_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_1",
    pcb_component_id: "pcb_component_0",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: 3.5,
    y: 0,
    source_port_id: "source_port_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_2",
    pcb_component_id: "pcb_component_1",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: -3.5,
    y: 0,
    source_port_id: "source_port_2",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_3",
    pcb_component_id: "pcb_component_1",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: -2.5,
    y: 0,
    source_port_id: "source_port_3",
  },
]

const circuitJsonWithTraceThickness2 = [
  {
    type: "source_port",
    source_port_id: "source_port_0",
    name: "pin1",
    pin_number: 1,
    port_hints: ["anode", "pos", "left", "pin1", "1"],
    source_component_id: "source_component_0",
  },
  {
    type: "source_port",
    source_port_id: "source_port_1",
    name: "pin2",
    pin_number: 2,
    port_hints: ["cathode", "neg", "right", "pin2", "2"],
    source_component_id: "source_component_0",
  },
  {
    type: "source_component",
    source_component_id: "source_component_0",
    ftype: "simple_resistor",
    name: "R1",
    resistance: 1000,
    display_resistance: "1kΩ",
  },
  {
    type: "source_port",
    source_port_id: "source_port_2",
    name: "pin1",
    pin_number: 1,
    port_hints: ["anode", "pos", "left", "pin1", "1"],
    source_component_id: "source_component_1",
  },
  {
    type: "source_port",
    source_port_id: "source_port_3",
    name: "pin2",
    pin_number: 2,
    port_hints: ["cathode", "neg", "right", "pin2", "2"],
    source_component_id: "source_component_1",
  },
  {
    type: "source_component",
    source_component_id: "source_component_1",
    ftype: "simple_capacitor",
    name: "C1",
    capacitance: 1e-9,
    display_capacitance: "1nF",
  },
  {
    type: "source_group",
    source_group_id: "source_group_0",
    is_subcircuit: true,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_0",
    connected_source_port_ids: ["source_port_0", "source_port_2"],
    connected_source_net_ids: [],
    max_length: null,
    display_name: ".R1 > .pin1 to .C1 > .pin1",
    subcircuit_connectivity_map_key: "unnamedsubcircuit27_connectivity_net0",
    min_trace_thickness: 0.15,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_0",
    center: {
      x: 3,
      y: 0,
    },
    width: 1.5999999999999996,
    height: 0.6000000000000001,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_0",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_1",
    center: {
      x: -3,
      y: 0,
    },
    width: 1.5999999999999996,
    height: 0.6000000000000001,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_1",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_board",
    pcb_board_id: "pcb_board_0",
    center: {
      x: 0,
      y: 0,
    },
    thickness: 1.4,
    num_layers: 4,
    width: 10,
    height: 10,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_0",
    pcb_component_id: "pcb_component_0",
    pcb_port_id: "pcb_port_0",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["1", "left"],
    x: 2.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_0",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: 2.5,
    y: 0,
    pcb_component_id: "pcb_component_0",
    pcb_smtpad_id: "pcb_smtpad_0",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_1",
    pcb_component_id: "pcb_component_0",
    pcb_port_id: "pcb_port_1",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["2", "right"],
    x: 3.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_1",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: 3.5,
    y: 0,
    pcb_component_id: "pcb_component_0",
    pcb_smtpad_id: "pcb_smtpad_1",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_2",
    pcb_component_id: "pcb_component_1",
    pcb_port_id: "pcb_port_2",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["1", "left"],
    x: -3.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_2",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: -3.5,
    y: 0,
    pcb_component_id: "pcb_component_1",
    pcb_smtpad_id: "pcb_smtpad_2",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_3",
    pcb_component_id: "pcb_component_1",
    pcb_port_id: "pcb_port_3",
    layer: "top",
    shape: "rect",
    width: 0.6000000000000001,
    height: 0.6000000000000001,
    port_hints: ["2", "right"],
    x: -2.5,
    y: 0,
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_3",
    layer: "top",
    shape: "rect",
    width: 0.42000000000000004,
    height: 0.42000000000000004,
    x: -2.5,
    y: 0,
    pcb_component_id: "pcb_component_1",
    pcb_smtpad_id: "pcb_smtpad_3",
    subcircuit_id: "subcircuit_source_group_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_0",
    pcb_component_id: "pcb_component_0",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: 2.5,
    y: 0,
    source_port_id: "source_port_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_1",
    pcb_component_id: "pcb_component_0",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: 3.5,
    y: 0,
    source_port_id: "source_port_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_2",
    pcb_component_id: "pcb_component_1",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: -3.5,
    y: 0,
    source_port_id: "source_port_2",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_3",
    pcb_component_id: "pcb_component_1",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_0",
    x: -2.5,
    y: 0,
    source_port_id: "source_port_3",
  },
]
